# plasmidBin provenance — build traceability
generated = "2026-06-09T13:03:50Z"
builder = "unknown"
target = "x86_64-unknown-linux-musl"
rustc = "rustc 1.96.0 (ac68faa20 2026-05-25)"

[barracuda]
commit = "9b9cbed3"

[beardog]
commit = "d3a8eb7b"

[biomeos]
commit = "a459ec58"

[coralreef]
commit = "4c417a95"

[loamspine]
commit = "d74342d5"

[nestgate]
commit = "4258ce46"

[petaltongue]
commit = "6ea64799"

[rhizocrypt]
commit = "133dd23c"

[skunkbat]
commit = "7ae3c82c"

[songbird]
commit = "aebe271f"

[sourdough]
commit = "bbc4821"

[squirrel]
commit = "ac8ef9c8"

[sweetgrass]
commit = "85397dd3"

[toadstool]
commit = "ad0c81ca1"

