# plasmidBin provenance — build traceability
generated = "2026-06-15T13:37:17Z"
builder = "unknown"
target = "x86_64-unknown-linux-musl"
rustc = "rustc 1.96.0 (ac68faa20 2026-05-25)"

[barracuda]
commit = "62b58083"

[beardog]
commit = "eff59c43"

[biomeos]
commit = "1ce2a4c5"

[coralreef]
commit = "68c302ea"

[loamspine]
commit = "ea37a27d"

[nestgate]
commit = "17baed59"

[petaltongue]
commit = "cdcb1ee6"

[rhizocrypt]
commit = "3a5ae6d2"

[skunkbat]
commit = "6fbdc43a"

[songbird]
commit = "78c14667"

[sourdough]
commit = "bbc4821"

[squirrel]
commit = "c94090c9"

[sweetgrass]
commit = "e8805233"

[toadstool]
commit = "62592ec4"

