# golgiBody WireGuard hub peer block
# Pre-generated for gate enrollment — append to /etc/wireguard/wg0.conf

[Peer]
PublicKey = A2fvz3czkqRUuu2mzkSS6IVr/TCQcpsJX9HbDBa1FBc=
Endpoint = 157.230.3.183:51820
AllowedIPs = 10.13.37.0/24
PersistentKeepalive = 25
